# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_auto_20160803_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
