# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0004_auto_20160810_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archive_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='wayback',
            field=models.CharField(max_length=300, null=models.URLField(null=True)),
        ),
        migrations.AddField(
            model_name='url',
            name='wayback_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
